### ISSUE TITLE
Flood of parsing recipe errors using sync@1.2

### ISSUE THREAD

**Issue by 0x07cf-dev** [Kira-NT/smart-recipes#1]
I noticed a massive flood of errors in my server's console referencing `dev.kirantipov.smartrecipes.api` so I looked you up on GitHub and I figured it had to do with this mod, specifically version 1.2, as this does not happen using the previous release.

The errors are all mostly the same, the majority of which references `charm` recipes.
`[Worker-Main-7/ERROR]: Parsing error loading recipe charm:woodcutters/birch_planks_from_birch_wood`

To keep things short, here's the logs my friend: [1.1](https://gist.github.com/0x007CF/f54cc80f0732a58e3973a2c6c70f815b#file-sync-1-1-log) - [1.2](https://gist.github.com/0x007CF/f54cc80f0732a58e3973a2c6c70f815b#file-sync-1-2-log)
Enjoy the weekend 😄

**Comment by Kira-NT** [comment]
> this does not happen using the previous release

Because previous release doesn't use SmartRecipes :D

General incompatibility with `net.minecraftforge.common.crafting.CraftingHelper` *(don't even know the heck is this in terms of Fabric)*: we both use `conditions` property to determine whether the recipe should be loaded. Also, I'm currently working on the `template` property for the recipe format. So I can ensure you, that it will be even worse :)

The best I can do is disable logger when this thing is loaded. Don't like this option too much, though

**Comment by Kira-NT** [comment]
Hi! The newest version of Smart Recipes *(0.1.1)* has `debug` config option. Set this one to `false` in order to get rid of the flood.

Config may be found at `./config/smart-recipes.properties`.
